### PR TITLE
add mitmproxy

### PR DESCRIPTION
**Pull request by HarrisChu**
Add the mitmproxy to record http requests and then dump to HAR file

### CODE REVIEW

**Comment by debugtalk** [comment]
@HarrisChu Thanks for your pull request.

However, I do not think this feature should be merged into HttpRunner. What this feature does is similar to Charles/Fiddler, and it should be kept independent.

**Comment by HarrisChu** [comment]
OK

It's convenience for me than Charles. Just share it

**Comment by sandeepmobicom** [comment]
@HarrisChu : After filtering I could only see the request API details on HAR file not the corresponding response. How do I get both Request and Response of filtered API.

**Comment by debugtalk** [comment]
@sandeepmobicom Which proxy tool do you use? In my case, Charles or Fiddler are both working perfectly.

**Pull request closed without merging**
